services:
  # PostgreSQL Database
  - type: pserv
    name: coding-challenge-platform
    env: python
    plan: free

  # Web Service (Backend + Frontend)
  - type: web
    name: coding-challenge-platform
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: coding-challenge-db
          property: connectionString
